### ISSUE TITLE
Any scheduled release date ?

### ISSUE THREAD

**Issue by jalchr** [neo4j/neo4j-dotnet-driver#1]
Hi,
Thanks for building a native .net driver for neo4j. Its more exciting to see that it is built for version 3.0.
Can we expect, hopefully, to see it released along the production version of neo4j?

Thanks,

**Comment by zhenlineo** [comment]
Yes, the driver would be release along with neo4j-3.0 (or shortly a few day after). A few pre-releases are coming soon if you would like to try it out before 3.0 :)

**Comment by cskardon** [comment]
You can try the M01 release via Nuget (https://www.nuget.org/packages/Neo4j.Driver)

**Comment by jalchr** [comment]
sure I'll try it ... great  work guys
