### ISSUE TITLE
neo4j driver from powershell fails

### ISSUE THREAD

**Issue by eosfor** [neo4j/neo4j-dotnet-driver#100]
```
using assembly "C:\Program Files\NuGet\Packages\Neo4j.Driver.1.1.0-M01\lib\dotnet\Neo4j.Driver.dll"
using assembly "C:\Program Files\NuGet\Packages\rda.SocketsForPCL.2.0.1-pre\lib\net45\Sockets.Plugin.Abstractions.dll"
using assembly "C:\Program Files\NuGet\Packages\rda.SocketsForPCL.2.0.1-pre\lib\net45\Sockets.Plugin.dll"

using namespace Neo4j.Driver.V1

$driver = [GraphDatabase]::Driver('bolt://192.168.0.104'),[authtokens]::Basic('neo4j','somepass#'))

$driver.Session()
```

and what I get is

> Exception calling "Session" with "0" argument(s): "One or more errors occurred."
> At line:1 char:1
> - $driver.Session()
> - ~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
>   - FullyQualifiedErrorId : AggregateException

there are some additional details, if I do this right after call fails i see

> PS C:\Windows\system32> $Error[0].Exception.InnerException.InnerExceptions
> Method not found: 'System.Threading.Tasks.Task Sockets.Plugin.Abstractions.ITcpSocketClient.ConnectAsync(System.String, Int32, Boolean)'.

PS: neo4j community edition running on ubuntu

**Comment by zhenlineo** [comment]
This line `Sockets.Plugin.Abstractions.ITcpSocketClient.ConnectAsync(System.String, Int32, Boolean)` indicates something is wrong with `rda.SocketsForPCL`. 
Try PCL version `1.2.2` first. I have `1.2.2` imported. Maybe they changed some interfaces in 2.0

**Comment by eosfor** [comment]
This looks better, thanks
