### ISSUE TITLE
Does not support TLS1.2

### ISSUE THREAD

**Issue by umutsayar** [neo4j/neo4j-dotnet-driver#104]
I can not use GrapheneDB services because they does not support TLS 1.0 for security reasons. They require TLS 1.1 and TLS 1.2. GrapheneDB services (with bolt protocol) can not be used while "Neo4j .NET Driver" supports only TLS 1.0.

**Comment by technige** [comment]
A release of the driver that supports TLS 1.2 is in the pipeline and should be released within the next few weeks.

**Comment by zhenlineo** [comment]
The new .Net driver 1.1.0-M02 will have the support of TLS 1.2 https://github.com/neo4j/neo4j-dotnet-driver/pull/103
