### ISSUE TITLE
handle dependency with correct "rda.SocketsForPCL" nuget package

### ISSUE THREAD

**Issue by genez** [neo4j/neo4j-dotnet-driver#105]
Current Neo4j.Driver nuget package (1.1.0-M01) has a dependency on rda.SocketsForPCL (>= 1.2.2)
Unfortunately, latest rda.SocketsForPCL version (2.0.2) is not compatible and the driver throws a MissingMethodException at runtime.

Please fix the dependency or upgrade to latest rda.SocketsForPCL version

**Comment by zhenlineo** [comment]
Thanks for bring this issue up. We are currently working on next release to remove the dependency of rda.SocketsForPCL and switch to .net core sockets.

**Comment by zhenlineo** [comment]
The new 1.1.0-M02 driver will be free of PCL, and switch to .net core libs.
