### ISSUE TITLE
dotnet run fails on ubuntu 16 and dotnet-dev-1.0.0-preview2-003131

### ISSUE THREAD

**Issue by genez** [neo4j/neo4j-dotnet-driver#114]
I have created a simple test application with visual studio 2015
then referenced Neo4j driver version 1.1.0-m02 (using Nuget pre-release)
I copied the test program from another project using Mono and driver version 1.1.0-m1.
I am able to successfully compile and execute the new binary in windows.
On linux I get this error after "dotnet run" command:

```
genesio@neo01:/opt/neo4jtest/netcore/src/Neo4jTestNetCore$ dotnet run
Project Neo4jTestNetCore (.NETCoreApp,Version=v1.0) will be compiled because the version or bitness of the CLI changed since the last build
Compiling Neo4jTestNetCore for .NETCoreApp,Version=v1.0
/opt/neo4jtest/netcore/src/Neo4jTestNetCore/project.json(12,31): error NU1001: The dependency Neo4j.Driver >= 1.1.0-M02 could not be resolved.

Compilation failed.
    0 Warning(s)
    1 Error(s)
```

Executing "dotnet restore" does not fix the problem:

```
genesio@neo01:/opt/neo4jtest/netcore/src/Neo4jTestNetCore$ dotnet restore
log  : Restoring packages for /opt/neo4jtest/netcore/src/Neo4jTestNetCore/project.json...
log  : Lock file has not changed. Skipping lock file write. Path: /opt/neo4jtest/netcore/src/Neo4jTestNetCore/project.lock.json
log  : /opt/neo4jtest/netcore/src/Neo4jTestNetCore/project.json
log  : Restore completed in 683ms.
```

I had to open manually edit the "project.json" file and change the dependency section from this

```
"dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0"
    },
    "Neo4j.Driver": "1.1.0-M02"
  },
```

to this:

```
"dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0"
    },
    "Neo4j.Driver": "1.1.0-m02"
  },
```

please note UPPERCASE `1.1.0-M02` in original project.json file

then it works

**Comment by zhenlineo** [comment]
Thanks for this feedback. I need to read more about the new versioning. The next version will have a correct version name in it.

**Comment by zhenlineo** [comment]
Thanks for the feedback, I am closing this issue as we've change the version name to m03 this time.  Pls be free to re-open this issue if you still have any issue with it.
