### ISSUE TITLE
Too many dependencies when using net framework.

### ISSUE THREAD

**Issue by SpencerJB** [neo4j/neo4j-dotnet-driver#158]
Hi, I am using the neo4j driver on a .net 4.6 project and when I use nuget to pull in the neo driver I also pull in a lot of dependencies with the .netstandard library that are unecessary. 

I've looked at the nuspec file and I can remove a lot of those dependencies by adding 
```
   <dependencies>
          <group targetFramework="net">
            <dependency id="System.Net.Security" version="4.0.0" />
            <dependency id="System.Net.Sockets" version="4.1.0" />
          </group>
```
and 
```    
    <files>
        <file src="Neo4j.Driver\bin\$configuration$\Neo4j.Driver.dll" target="lib\net" />
        <file src="Neo4j.Driver\bin\$configuration$\Neo4j.Driver.pdb" target="lib\net" />
        <file src="Neo4j.Driver\bin\$configuration$\Neo4j.Driver.xml" target="lib\net" />
```

So that only needed dependencies are pulled in. Would it be possible to make changes to the nuspec file in the project?

Spencer.

**Comment by zhenlineo** [comment]
Sorry for the late reply, I will have a look this week and try to fix it in next release.

**Comment by zhenlineo** [comment]
Check out the [1.3.0-beta01 release](https://github.com/neo4j/neo4j-dotnet-driver/releases/tag/1.3.0-beta01). The dependency problem should be go away from this 1.3 series.
