### ISSUE TITLE
.Net is not fully supported 

### ISSUE THREAD

**Issue by ChaosYoda** [neo4j/neo4j-dotnet-driver#159]
I tried to create a VC++ CLR project which still falls under .Net and I got the error  "Could not install package 'Neo4j.Driver 1.2.0'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author." when trying to install the package.

**Comment by zhenlineo** [comment]
Sorry for the inconvenient, I will look into this.

**Comment by cskardon** [comment]
Hi @Tazmain  - Can you add a reference to `System.Net.Security` in the C++ CLR project?

**Comment by ChaosYoda** [comment]
It is possible to add the System.Net.Security dll manually, it seems to be a problem with Nuget for VC++. Is there a way to just download the .dll file?

**Comment by cskardon** [comment]
There isn't a `dll` version - as `Neo4j.Driver` is distributed exclusively by nuget, so you have 2 options:

1) download the package into a C# project, then you should have the dll in the `packages` folder of that project, or
2) follow the instructions in: http://stackoverflow.com/questions/18694947/how-can-i-make-my-managed-nuget-package-support-c-cli-projects

I'm not sure which is easiest for you, I presume that `2` allows you to restore the packages and keep up to date, even if you have to use `nuget` manually, and `1` means you have to maintain that chain yourself. 

Unfortunately there is nothing that a package author can do about this - as it's a `nuget` issue (as you correctly point out)

**Comment by ChaosYoda** [comment]
So I can add the .dll and start to use it. Will see if I can get it instantiated with C++/CLI and get a result.

**Comment by cskardon** [comment]
If /when you do, I'd love to see a simple "hello world" example, I've really got no idea how to use it from c++

**Comment by ChaosYoda** [comment]
I am just getting stuck with the AuthTokens, I cannot cast AuthTokens to IAuthToken. Creating a Driver instance requires this if I want to authenticate myself. I have a hello world compiling, just need to figure out the System.Net.Sockets dll load issue.

**Comment by zhenlineo** [comment]
@Tazmain `AuthTokens` is not a `IAuthToken`. AuthTokens is a class provides static methods to create `AuthToken`. So you need to either use `AuthTokens` to create a `AuthToken` to cast to `IAuthToken` or create a `AutoToken` yourself if you have access to that class.

**Comment by ChaosYoda** [comment]
So as it turns out I can use the .dll but because of its dependencies, it fails to load those, since it is looking for the nuget versions of System.Net.Sockets. If that was removed I would be able to use it. It is also possible to create a nuget package compatible with Visual C++. For now, I suggest just updating the webiste to not say .Net compatible but C# .Net compatible rather, being specific. As .Net compatible includes Visual C++.

**Comment by cskardon** [comment]
How is it possible to create a nuget package that works with C++, if you could share that it'd be super useful to be able to get it working.

**Comment by bytebuilder26** [comment]
It doesn't work for me either when trying to add the package to a Xamarin Forms app. Has anyone been successful adding the driver to other platforms?

I'm getting this:
![image](https://user-images.githubusercontent.com/20599359/28995630-8a72d94a-79b3-11e7-9e41-de6a282bb64b.png)

thanks!

**Comment by ali-ince** [comment]
Hi @bytebuilder26,

The Neo4j.Driver package targets .NET Standard 1.3 and the runtimes that supports it could be found [here](https://github.com/dotnet/standard/blob/master/docs/versions.md). PCL profile 259 is logically equal to .NET Standard 1.0 and an exhaustive list of profiles and their corresponding .NET Standard levels could be found [here](https://blog.stephencleary.com/2012/05/framework-profiles-in-net.html). Although we have a plan to support .net 4.5.2, we probably will not be targeting .Net Standard versions less than 1.3.

Ali

**Comment by ChaosYoda** [comment]
If dotnet core is going to be the target for the future, then having it working with C++ might be a problem since dotnet core will not support VC++.

**Comment by ali-ince** [comment]
Hi @Tazmain,

Latest 1.4.1 release and 1.5.0 pre-releases targets both .net 4.5.2 and .net standard 1.3. With explicit support for .net 4.5.2 you can manually reference it in your C++/CLI project (as nuget is not supported on C++ projects) and make use of it as an ordinary class library.

Please also note that we have incorporated more compatibility changes (changing optional arguments to method overloads) in the latest 1.4.1 release for better integration in other .NET languages other than C# and VB.

Ali

**Comment by ali-ince** [comment]
Hi @bytebuilder26,

Please be informed that our latest 1.4.1 release targets .net framework 4.5.2 and .net standard 1.3. With this improvement, you may retry your usage scenario in Xamarin Forms by selecting a PCL profile that supports .net framework 4.5.2.

Ali
