### ISSUE TITLE
Query Results Returning Blank

### ISSUE THREAD

**Issue by corygehr** [neo4j/neo4j-dotnet-driver#174]
In v1.2 of the driver my resultsets are coming up empty. The code used is similar to the following:

```
            using (ISession session = client.Session())
            {
                IStatementResult result = session.Run("MATCH (a:Person)-[b:FRIENDS_WITH]->(c:Person) RETURN a,b,c");

                foreach (var evt in result)
                {
                    // Do something with results
                }
```

I don't even get to enumerate the results in this case. Running the same query directly on the DB is fine.

Also of note - when I use the debugger in VS I can expand the results view but it just shows a bunch of empty entries (I suspect the number of empty rows matches the number of results I'm expecting, but the Summary object doesn't reference the number of edges and nodes matched from the query).

Is there something different I should be doing to query the database in 1.2? The documentation on the Neo4j website doesn't seem to indicate anything has changed although I've noticed in the Wiki that there is now support for streaming data. Glancing at the source code quickly doesn't reveal anything that might be different.

**Comment by corygehr** [comment]
Updating to mention that this is an issue with all driver versions >=1.1

**Comment by corygehr** [comment]
Ah, so it was the streaming data that bit me here - missed the info on enumerating the results via something like .ToList() before you can consume the data. Would be helpful to update the Wiki with this as the current info there doesn't require this.

**Comment by zhenlineo** [comment]
Hi,

One note: 
If you call ToList(), all the records will be buffered into a list. 
If you could process each record when you are enumerating, then it will save you some memory use.

**Comment by corygehr** [comment]
@zhenlineo My issue is that the enumeration wouldn't even start - I need to call ToList() to get any data out of the StatementResult object. Is there something I need to call on the StatementResult object in order to populate the results?

This could be a .NET 4.6.2 issue but as stated above, the Debugger just showed a bunch of blank results when I expanded that view.

**Comment by zhenlineo** [comment]
@corygehr You should be able to "stream" over the result. That is for each iteration, you will receive one record until you reached the end of the stream. And if you did not save the record you received in the current iteration, you cannot get it back once you iterated over it. (That's why you might want to call ToList to buffer all records into memory if you need to go back to the stream)

Can you run the following code example?

```
// first create some record in the database:
// "CREATE (a:Person {name: 'Alice'})"
// "CREATE (a:Person {name: 'Bob'})"
// Then try to steaming the records:
using (var session = client.Session())
{
    var result = session.Run("MATCH (a:Person) RETURN a.name ORDER BY a.name");
    foreach (var record in result)
    {
        Console.WriteLine(record[0].As<string>()); //can only do something to the current record
    }
}
```

**Comment by corygehr** [comment]
@zhenlineo Yep - this is exactly what I was doing previously. However, the enumeration would never run even though the debugger showed empty result rows, but perhaps because the result was not yet streamed or all the objects were empty, `.Count()` was returning 0 since the resultset technically looked to be empty.

Again, could be a .NET 4.6.2 compatibility issue but the exact code you have there is what I was trying to do. It just never entered the foreach loop to stream the individual record.

**Comment by corygehr** [comment]
@zhenlineo We can reopen this if you'd like, but for some reason doing `.ToList()` worked so maybe my thoughts above aren't the exact issue.

**Comment by zhenlineo** [comment]
Could you give me the version of the driver you are using?
I might setup a simple 4.6.2 project sometime to see if there is an issue or not.

**Comment by corygehr** [comment]
1.2.1, although I was having issues with all releases >=1.1 when I was checking backwards compatibility. Up to 1.0.2 that code was fine.
