### ISSUE TITLE
Will neo4j .net driver support .net framework version 3.5?

### ISSUE THREAD

**Issue by elvindp** [neo4j/neo4j-dotnet-driver#237]
I try to involve neo4j using Unity but I find the highest .net framework version of Unity is 3.5, which is unable to use this driver. Therefore, I wonder whether there are any ways to solve this problem? I would be very appreciate if you could help me. Thanks!

**Comment by zhenlineo** [comment]
The current plan is only .NET framework 4.5.2 and .Net Standard 1.3

**Comment by zhenlineo** [comment]
Right now as we moved to async, we cannot support 3.5 in newer driver version.
