### ISSUE TITLE
What is the idea of how to read values values out of PackStreamStruct?

### ISSUE THREAD

**Issue by flq** [neo4j/neo4j-dotnet-driver#244]
Consider the following  statement:

```
MATCH (p:Person)-[r:OWNS]->(n) 
WITH p, collect(n) as products
WHERE id(p) = {id} RETURN p, products
```

Here the _products_ key will point to a `List<object>` whose elements are `Node`s, fair enough.

Now, suppose I also need relationship info and do something like this:

```
MATCH (p:Person)-[r:OWNS]->(n) 
WITH p, collect({ rel: r, product: n }) as products
WHERE id(p) = {id} RETURN p, products
```

What I now get is

```
((Dictionary<string,object>)((List<object>)result[0]["products"])[0]).Values
Count = 2
    [0]: {Neo4j.Driver.Internal.IO.PackStreamStruct}
    [1]: {Neo4j.Driver.Internal.IO.PackStreamStruct}

```
And here I cannot sensibly access the values of **rel** and **product** anymore because the value is represented with an internal object.

If you tell me that this is a fairly stable API I can drill holes into it to extract the values, but maybe you tell me that you will actually make those items public?

Looking forward to any pointers

**Comment by zhenlineo** [comment]
`PackStreamStruct` should stay internal. We probably exposed the wrong type here. Working on a fix now.

Thanks so much for reporting to us!
Zhen

**Comment by flq** [comment]
Thank you Zhen,
as an aside I was looking at whether I can put myself in the position to contribute since my current "pet" project involves knowing the .NET Neo Driver pretty well - running the integration & TCK(?) tests, it appears that you require access to some AWS resources...

`Required environment variable is not defined: AWS_ACCESS_KEY_ID`

However, the "Tests" project runs fine.

**Comment by zhenlineo** [comment]
@flq Yeah, IT and TCK tests requires aws to download a server to run all tests unless you have already downloaded a server by running tests before. You could probably run most of IT and TCK tests if you have a community server in the path `github-parent-folder/Target/neo4jhome`, with password `neo4j` (See more in this [class](https://github.com/neo4j/neo4j-dotnet-driver/blob/230d8cefabc2d8c5c76db42c50049ac843c0d6c0/Neo4j.Driver/Neo4j.Driver.IntegrationTests/Internals/StandAlone/ExternalBoltkitInstaller.cs)). But any ITs that has `RoutingDriver` or `Cluster` in its name still requires a enterprise server.

I will also fix this by allow a user to provide a file path to download server in boltkit later.

Be free to start a PR and send us a [CLA](https://neo4j.com/developer/cla/), then your PR will be built by our build server.

**Comment by flq** [comment]
Looks like the PR is merged, and it is already in the Nuget - I think that is nothing short of awesome, folkes. Thank you!
I should be able to give it a spin this evening and see how it behaves :)

**Comment by flq** [comment]
Okay...um, color me confused. I look at the Driver code, it does not have `PackStreamStruct` anymore, I see that the code is tagged 1.5.0-rc1, as the nuget. I updated the nuget reference, removed older versions from the cache at  `%userprofile%\.nuget\packages` - deleted obj, rebuilt...but I still get PackstreamStructs back with the opening cypher statement above.

Is the code not in the nuget yet?

**Comment by zhenlineo** [comment]
Sorry, I messed up tags, rc1 has not got the fix in yet. It will come with rc2 very soon. See the [changelog](https://github.com/neo4j/neo4j-dotnet-driver/wiki/1.5-changelog)

If you would like to try it right now. You could play with our mygut feed to try out with a snapshot, see more info [here](https://github.com/neo4j/neo4j-dotnet-driver#snapshots)

Zhen

**Comment by flq** [comment]
I just tested with **1.5.0-rc2** and it is working as expected with nested nodes and relationships coming out as desired, or arbitrary values as a dictionary. From my point of view this could be closed.

Thank you very much, people 🥇
