### ISSUE TITLE
Updated from 1.3 to 1.5 - reference dlls missing in output folder?

### ISSUE THREAD

**Issue by MPasadu** [neo4j/neo4j-dotnet-driver#249]
We have multiple projects and one project has the neo4j nuget package and reference. **When referencing this project from other projects** the neo4j dll is copied to the outputfolder of the other projects. 
In version 1.3 all other referencing dlls that are used by the neo4j are also copied. 
In version 1.5 only the neo4j dll is copied.

This creates problems when trying to create our setup files since the dlls are missing in these folders.

I guess this is now intended?

**Comment by ali-ince** [comment]
Hi @MPasadu,

Since version 1.4.2, we explicitly started supporting .NET Framework 4.5.2+ and if you're developing on .NET Framework rather than .NET Core, the driver no longer requires those references.

Ali

**Comment by MPasadu** [comment]
Thank you for the fast response.

We will get rid of the references and push .NET Framework 4.5.2 as lowest requirement!
