### ISSUE TITLE
Unittests made with MSTest which is not supported in Xamarin

### ISSUE THREAD

**Issue by IngvarKofoed** [neo4j/neo4j-dotnet-driver#25]
I suggest using NUnit instead of MSTest for the unittest projects. This would make it possible for developers to open and run tests using Xamarin when developing on non Windows platforms.

If you agree, then I can make a pull request where the projects have been changed to use NUnit and tested in both Visual Studio and Xamarin :)

**Comment by cskardon** [comment]
It's using XUnit, not MSTest? Doesn't xunit work with xamarin? A brief search on google shows that it should...

Are you opening the project in xamarin studio?

**Comment by IngvarKofoed** [comment]
The problems is that the projects are created within Visual Studio so they will get an "Test" project type and Xamarin Studio can't handle this and will not load the project. The solution is to change the project type from MSTest project to NUnit project.

Yes, I open the solution in Xamarin Studio: http://imgur.com/VGH1HTO

More information about it here: https://forums.xamarin.com/discussion/22097/xamarin-studio-is-unable-to-open-test-project-created-in-visual-studio-2013

**Comment by cskardon** [comment]
Right, so you don't need to change to nunit, just remove the test guid from the csproj?

**Comment by IngvarKofoed** [comment]
That will fix the issue in XS. Ill try that and test how that works in VS and if it works, then create a PR :)

**Comment by cskardon** [comment]
I'm pretty certain that all it does is not show the test 'icon', so it should work fine!

**Comment by IngvarKofoed** [comment]
Yeah, I was hoping for the same thing, but it was not as easy. I had to create new projects because that Guid was not the only thing that made it not compile in Xamarin on OSX. I have all things compiling and all unittest working. Im working on running integration tests.

Some of the unittests fails because of Windows locale settings. Ill also fix those.

**Comment by IngvarKofoed** [comment]
This can be closed if PR #35 is merged :)

**Comment by zhenlineo** [comment]
Some updates on this issue:

The PR is red due to some lib missing (.NET Framework 4.5.1 SDK) on teamcity windows machine. So working on the machine right now.

**Comment by zhenlineo** [comment]
Hi 

Sorry for not come back for this PR for a long time. 

We looked into this issue and we find the support for compiling source code/run all unittests with Xamarin is not part of our current target. You are most welcome to issue a PR to add this support. But we currently will not add/maintain this feature. 

Cheer,
Zhen

**Comment by zhenlineo** [comment]
Hi, sorry for idle on this thread for too long. Right now supporting compiling the source code in another platform other than windows is not part of current plan. But you are most welcome to contribute to support compiling source code in other platforms.

Cheers,
Zhen
