### ISSUE TITLE
'Neo4j.Driver' does not have a strong name

### ISSUE THREAD

**Issue by d0pare** [neo4j/neo4j-dotnet-driver#251]
Are there any plans to create strong name for Neo4j.Driver assembly ?

**Comment by birop** [comment]
+1

**Comment by ali-ince** [comment]
Hi @dopare & @birop,

I would like to inform you that we now have a strong named snapshot version of the driver available on myget. The old nuget package named `Neo4j.Driver` will continue as it is, where our new nuget package named `Neo4j.Driver.Signed` will contain a strong named version.

As expected, these nuget packages are mutually exclusive.

You can try the snapshot release through our [snapshot release gallery](https://www.myget.org/gallery/neo4j-driver-snapshots) on myget. The package will show-up on nuget with our upcoming 1.6.0 GA release (due soon).

I'm now closing this issue, please feel free to update it if you find something missing.

Thanks for your feature request.

Neo4j Driver Team
