### ISSUE TITLE
Integration Tests require access to enterprise database and cluster

### ISSUE THREAD

**Issue by d0pare** [neo4j/neo4j-dotnet-driver#255]
I was trying to run tests on my local machine and encountered few issues
 1. Test setup by [default](https://github.com/neo4j/neo4j-dotnet-driver/blob/1.5/Neo4j.Driver/Neo4j.Driver.IntegrationTests/Internals/BoltkitHelper.cs#L27) is trying to [install](https://github.com/neo4j/neo4j-dotnet-driver/blob/1.5/Neo4j.Driver/Neo4j.Driver.IntegrationTests/Internals/StandAlone/ExternalBoltkitInstaller.cs#L54) enterprise database which can be overridden by creating environment variable `NeoctrlArgs = 3.2.1`
 2. Test setup is trying to install Neo4j cluster which is only enterprise. These tests can be manually skipped by changing `[RequireClusterFact]` to `[RequireClusterFact(Skip = "No cluster")]` and `[RequireClusterTheory]` to `[RequireClusterTheory(Skip = "No cluster")]` 
 3. Another thing which is required is JRE and JAVA_HOME environment variable

After all these changes I get authentication issues and I realized that [create user](https://github.com/neo4j/neo4j-dotnet-driver/blob/1.5/Neo4j.Driver/Neo4j.Driver.IntegrationTests/Internals/StandAlone/ExternalBoltkitInstaller.cs#L61) is not working so I [changed](https://github.com/dopare/neo4j-dotnet-driver/blob/3a405d4f9ee59d1938db22d7137604b3c50971df/Neo4j.Driver/Neo4j.Driver.IntegrationTests/Internals/StandAlone/ExternalBoltkitInstaller.cs#L61) it to only set initial password (`neotctrl-set-initial-password` has its own issues but it is not related to this repo) and it worked.

You can find all my changes in this [commit](https://github.com/dopare/neo4j-dotnet-driver/commit/3a405d4f9ee59d1938db22d7137604b3c50971df)

**Comment by zhenlineo** [comment]
Hi @dopare,

Sorry for the issue that you encountered while running tests locally. Currently the IT and TCK are running with enterprise server artifacts. Most of the integration tests should also be Okay to run with community server. The only problematic ones are the cluster tests which requires enterprise servers. I could make the driver tests to use community server and skip cluster tests for now. 

For your problem with boltkit, maybe try to use Python 2.7. It might be better tested on 2.7.

Cheers,
Zhen

**Comment by d0pare** [comment]
PR #258 will fix the issue.
Thanks @zhenlineo
