### ISSUE TITLE
Unable to retrieve CREATE / RETURN nodes and parse out their values

### ISSUE THREAD

**Issue by mwherman2000** [neo4j/neo4j-dotnet-driver#262]
Technically, when I call IStatementResult results = session.Run(...), the results.Keys array is being populated with the variable names of the nodes in the RETURN clause but I can't find a way to return the Nodes themselves.

Attached is a very simple .NET 1.5.2 console app using the current version of the .NET Client bolt driver.

[Neo4jClientTest2.zip](https://github.com/neo4j/neo4j-dotnet-driver/files/1511852/Neo4jClientTest2.zip)

NOTE: The credentials are for one of the Neo4j sandboxes.

**Comment by mwherman2000** [comment]
When I used a MATCH statement, I was able to retrieve and parse multiple IRecords.  I don't know if this is a bug/problem only when a CREATE statement (i.e. the nodes in the RETURN statement are not returned?).

Here is a working, more comprehensive C# sample.

[Neo4jClientTest2Works.zip](https://github.com/neo4j/neo4j-dotnet-driver/files/1511968/Neo4jClientTest2Works.zip)

**Comment by zhenlineo** [comment]
Hi @mwherman2000,

I had a quick look at your code. I think the reason that you have some problem with your queries is that the `Result` in this driver is streaming. We also designed it in a way that if you does not hold a copy of it, you could only iterate the records in the result stream once.

If your first code example. In line 20, where you have this
```Console.WriteLine("Result: " + results.Single().Values["tesla"].As<string>());```

When you did `results.Single()`, you already "consumed" the result stream.
If you want to revisit them, you should keep a local copy of it.

For your case, you probably want the code looks like this
```
IStatementResult results = session.Run("CREATE path=(baeldung:Company {name:\"Baeldung\"})" +
                            " -[:owns]-> " +
                            "(tesla:Car {make: 'tesla', model: 'modelX'})" +
                            "RETURN baeldung, tesla");
var records = results.ToList();
Console.WriteLine("Result: " + records.Single().Values["tesla"].As<string>());

List<string> keys = (List<string>)results.Keys;
// do more things with records
```

However for most of the cases, we suggest to only iterating the result once to avoid pulling too much data into the client buffer.

```
foreach(record in result)
{
   // do something to each record
}
```

For more examples, pls refer to our [driver docs](https://neo4j.com/docs/developer-manual/3.3/drivers/get-started/)

Cheers,
Zhen

**Comment by mwherman2000** [comment]
Thank you for the clarification, Zhen. Your explanation was very useful.
