### ISSUE TITLE
PackStreamWriter cannot write DateTime's

### ISSUE THREAD

**Issue by rdehuyss** [neo4j/neo4j-dotnet-driver#264]
When trying to save an object with a DateTime in it, I receive the following error 
```
Neo4j.Driver.V1.ProtocolException : Cannot understand value with type System.DateTime
```

**Comment by zhenlineo** [comment]
Hi @rdehuyss,

This driver only supports [Cypher types](https://neo4j.com/docs/developer-manual/3.3/drivers/cypher-values/).

Therefore this error is a expected behaviour. In order to save Date type, you probably want to convert it to a supported Cypher type before passing it to the driver.

Zhen

**Comment by zhenlineo** [comment]
Temporal type support added in this driver since https://github.com/neo4j/neo4j-dotnet-driver/pull/281

Please follow on news about Neo4j 3.4 releases and 1.6 driver releases where DateTime parameter type support would become available in Cypher.
