### ISSUE TITLE
Documentation for how to parse results

### ISSUE THREAD

**Issue by RMKD** [neo4j/neo4j-dotnet-driver#265]
This driver could really benefit from some more documentation (both in the readme and nuget) - especially in terms of parsing the result value.

**Comment by HassanHashemi** [comment]
yeah, this is really needed. specially since parsing result set is different based on the query result. (returning nodes, records, etc..)

**Comment by zhenlineo** [comment]
#290

**Comment by zhenlineo** [comment]
Hi @RMKD and @HassanHashemi,

Sorry for the long waiting. We've added more content in our project readme for [parsing results](https://github.com/neo4j/neo4j-dotnet-driver#parsing-result-values).

Thanks very much for your feedback.

Regards,
Zhen
