### ISSUE TITLE
[C# driver]Cannot break in the result foreach loop

### ISSUE THREAD

**Issue by lutovich** [neo4j/neo4j-dotnet-driver#276]
**Original issue**: https://github.com/neo4j/neo4j/issues/11116 raised by @ninaqms.

To help us understand your issue, please specify important details, primarily:

- Neo4j version: 1.5.2
- Operating system: windows 10
- API/Driver: .Net

Code:

```C#
using (var session = driver.Session())
{
    foreach(var sg in sgs)
    {
        var result = session.Run(string.Format(@"
          MATCH path = (sg:GROUP)< -[*] - (user:USER) 
          WHERE sg.SamAccountName = '{0}'
          RETURN user.SamAccountName as logon, EXTRACT(n in nodes(path) |  n.SamAccountName) as path, sg.SamAccountName as root", sg));
        foreach (var record in result)
        {
            List<string> path = record["path"].As<List<string>>();
            if (path.GroupBy(x => x).Any(g => g.Count() > 1))
            {
                break;
            }
            Console.WriteLine(string.Format("{0}\t{1}\t{2}", record["logon"].As<string>(), JsonConvert.SerializeObject(path), record["root"].As<string>()));
        }
    }
}
```

- **Steps to reproduce**
- Expected behavior
If the path contains loop, then exit the current foreach. The app consume to handle the next sg.

- Actual behavior
The application hang there, cannot execute the next session run.

**Comment by zhenlineo** [comment]
Tested with the following code:
```
            public void Test()
            {
                IRecord record = new Internal.Result.Record(
                    new List<string>{"path"},
                    new object[] {new List<string> {"1", "2", "3", "2", "1"}});
                List<string> path = record["path"].ValueAs<List<string>>();
                if (path.GroupBy(x => x).Any(g => g.Count() > 1))
                {
                    Console.WriteLine("Duplicate");
                }
            }
```
Did not see any problem. So maybe related to Cypher instead such as nodes(paths) returns infinite results or result really slow to compute answer.

So please either re-open the Neo4j issue at the Neo4j repo or give more information about where the execution hangs and if any result comes back to client or not.
