### ISSUE TITLE
Can't run integration unittests

### ISSUE THREAD

**Issue by IngvarKofoed** [neo4j/neo4j-dotnet-driver#28]
I have spend several hours trying to get the integration unittests to work. I'm running on a clean Windows 10 with Visual Studio 2015 Community and JRE 8. I'm running both VS, cosole and PS as administrator.

I have tracked down the issue to when the PS scripts tries to start the neo4j servies by debugging the unittest. Then I tried running the PS scripts manually and got the same error. Here is the log:

> PS C:\Sources\neo4j\original\neo4j-dotnet-driver\Neo4j.Driver\Neo4j.Driver.IntegrationTests\bin\target\neo4j\neo4j-commu
> nity-3.0.0-RC1\bin> Invoke-Neo4j start -v
> VERBOSE: Neo4j Root is 'C:\Sources\neo4j\original\neo4j-dotnet-driver\Neo4j.Driver\Neo4j.Driver.IntegrationTests\bin\target\neo4j\neo4j-community-3.0.0-RC1'
> VERBOSE: Neo4j Server Type is 'Community'
> VERBOSE: Neo4j Version is '3.0.0-RC1'
> VERBOSE: Neo4j Database Mode is ''
> VERBOSE: Start command specified
> VERBOSE: Neo4j Windows Service Name is neo4j
> VERBOSE: Starting the service.  This can take some time...
> Invoke-Neo4j : Failed to start service 'Neo4j Graph Database - neo4j (neo4j)'.
> At line:1 char:1
> - Invoke-Neo4j start -v
> - ~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>   - FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-Neo4j

It works if I get it to run as console: 

> PS C:\Sources\neo4j\original\neo4j-dotnet-driver\Neo4j.Driver\Neo4j.Driver.IntegrationTests\bin\target\neo4j\neo4j-community-3.0.0-RC1\bin> Invoke-Neo4j console -v
> VERBOSE: Neo4j Root is 'C:\Sources\neo4j\original\neo4j-dotnet-driver\Neo4j.Driver\Neo4j.Driver.IntegrationTests\bin\target\neo4j\neo4j-community-3.0.0-RC1'
> VERBOSE: Neo4j Server Type is 'Community'
> VERBOSE: Neo4j Version is '3.0.0-RC1'
> VERBOSE: Neo4j Database Mode is ''
> VERBOSE: Console command specified
> VERBOSE: Java detected at 'C:\Program Files\Java\jre1.8.0_73\bin\java.exe'
> VERBOSE: Java version detected as '1.8'
> VERBOSE: Starting Neo4j as a console with command line C:\Program Files\Java\jre1.8.0_73\bin\java.exe -cp
> "C:\Sources\neo4j\original\neo4j-dotnet-driver\Neo4j.Driver\Neo4j.Driver.IntegrationTests\bin\target\neo4j\neo4j-community-3.0.0-RC1/lib/_;C:\Sources\neo4j\original\neo4j-dotnet-driver\Neo4j.D
> river\Neo4j.Driver.IntegrationTests\bin\target\neo4j\neo4j-community-3.0.0-RC1/plugins/_" -server -Dorg.neo4j.config.file=conf/neo4j.conf -Dlog4j.configuration=file:conf/log4j.properties
> -Dneo4j.ext.udc.source=zip-powershell -Dorg.neo4j.cluster.logdirectory=data/log -Dorg.neo4j.config.file=conf/neo4j.conf -XX:+UseG1GC -XX:-OmitStackTraceInFastThrow -XX:hashCode=5
> -XX:+AlwaysPreTouch -XX:+UnlockExperimentalVMOptions -XX:+TrustFinalNonStaticFields -XX:+DisableExplicitGC -Dunsupported.dbms.udc.source=zip -Dfile.encoding=UTF-8
> org.neo4j.server.CommunityEntryPoint
> 2016-03-21 09:06:23.118+0000 INFO  Starting...
> 2016-03-21 09:06:31.680+0000 INFO  Started.
> 2016-03-21 09:06:34.633+0000 INFO  Remote interface available at http://localhost:7474/

I have also tried starting the service manually from Windows Services, but got this message: 

> The Neo4j Graph Database - neo4j service on Local Computer started and then stopped. Some services stop automatically if they are not in use by other services or programs.

I would really like to get them running, so I can contribute to the project :)

Any suggestions?

**Comment by zhenlineo** [comment]
Hello, I looked into your problem yesterday and it seems you have some problem with `Write-Error` command used in our powershell script. The build also have some problem to use the recent powershell script so I am also wondering if I should just switch to use the bat file instead to avoid these changes to disturb the normal driver code. I am working on this problem and I will come back to you once I got a solution or work around. Will ping you when the build is ready for your PR. 

Finally thanks a lot for the PRs.

**Comment by IngvarKofoed** [comment]
Thanks for you feed back! Using the BAT file might fix the issues I have seen :)

As you might have seen by now, I have created a PR that does not use PS or the Windows Service for running the Neo4j server. I have tested this on 3 Window PCs and worked on them all - When using the original code, integration tests did not work on any of the 3 PCs. You can consider using this when not running on the build server (eg local testing) and use the original when running on the build server :)

**Comment by zhenlineo** [comment]
https://github.com/neo4j/neo4j-dotnet-driver/pull/33

**Comment by zhenlineo** [comment]
As the pr is already merged in, I will close this issue now.
Feel free to reopen it when you got problem again,
