### ISSUE TITLE
Why doesn't StatementResultCursor implement IEnumerable?

### ISSUE THREAD

**Issue by nad-au** [neo4j/neo4j-dotnet-driver#333]
Would be more useful when enumerating results to use the standard enumerator as StatementResult does instead of using FetchAsync / Current.

Forgive me if I've overlooked something but couldn't an enumerator be implemented which simply calls FetchAsync and Yields a Current value?

**Comment by nad-au** [comment]
I think I know why. async / await and IEnumerable / yield don't go well together. Happy to close if there's no further comment from the team.
I'm working on a new project [Neo4jMapper](https://github.com/neildobson-au/Neo4jMapper) and I want to find the most efficient way of asynchronously mapping the result stream without having to read the entire result as a list in memory.

**Comment by zhenlineo** [comment]
Hi @neildobson-au,

Besides the async api we also provides a sync api `IStatementResult` where you have access to `IEnumerable`. The result is still lazily pulled there, so if you add callback for each record received, then you will avoid pulling the whole result into memory.

```
    class MyStatementResult<T> : IEnumerable
    {
        private IStatementResult _delegate;
        private Func<IRecord, T> _callback;

        public MyStatementResult(IStatementResult result, Func<IRecord, T> callback)
        {
            _delegate = result;
            _callback = callback;
        }

        public IEnumerator<T> GetEnumerator()
        {
            foreach (var record in _delegate)
            {
                yield return _callback(record);
            }
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }
```

If you still want to stick to the async API, then you can still register a callback function for each record to avoid pulling everything into memory. 

Hope this help with your Mapper. You can also have a look at https://github.com/Readify/Neo4jClient. They have some mapping built in out of box.

Regards,
Zhen
