### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Legolash2o** [neo4j/neo4j-dotnet-driver#347]
Can I request to have a method get that easily get the indexes on the database. 

graphClient.Cypher.GetIndexes()

It will return an array for objects such as

public class Index
{
   public string Node {get; }
   public string Property {get; }
   public bool Constraint {get; }
   ....
}

**Comment by ali-ince** [comment]
We do not provide wrapper operations inside the official driver.

I assume you meant to create an issue for https://github.com/Readify/Neo4jClient?
