### ISSUE TITLE
Support for connection to Neo4j Aura

### ISSUE THREAD

**Issue by davidwandar** [neo4j/neo4j-dotnet-driver#365]
Driver version**: .NET driver 4.0.0-alpha
.Net Core 2.2 web api

It would be great if the v4-driver would support connecting to the new Neo4J Aura service, from what I understand, that is not yet supported, which would mean that I currently need to downgrade my .NET Core -version to 1.0 (lame) and use the 1.7.2-driver instead.

**Comment by zhenlineo** [comment]
Hi @davidwandar ,
First a warning that the 4.0.0 drivers are still in pre-release stages, it is not yet ready for production use. You can of course using it in your development, but pls keep in mind the API is not stable yet.

Then for Aura support, the new 4.0.0 drivers shall support Neo4j Aura. We just put out a new `beta01`, could you give it a try and let us know if it works as expected?

The new 4.0 drivers does not have encryption on by default, while I think Neo4j Aura may enforce encrypted connections by default. So if you encounter any connection issues, check if your encryption settings are correct on two sides.

The full changelog can be found [here](https://github.com/neo4j/neo4j-dotnet-driver/wiki/4.0-changelog)

Cheers,
Zhen

**Comment by davidwandar** [comment]
Thanks for the response. I just realised that Neo4j Aura appears to be running v3.5 wich would exclude itself from this driver, correct?

**Comment by zhenlineo** [comment]
Hi @davidwandar,

4.0 driver supports 3.5 and 4.0 servers. But when using the driver with 3.5, you cannot use features only supported by 4.0 servers such as reactive and multi-database (database names).

Cheers,
Zhen

**Comment by davidwandar** [comment]
Thanks for your help. I am now up and running on the new beta 👍

**Comment by zhenlineo** [comment]
Hi @davidwanda,
I am closing this issue as it seems your problem has been solved. Let us know if you found anything while using this driver.

Cheers,
Zhen
