### ISSUE TITLE
Any instruction on how to upgrade to 4.0.0 ?

### ISSUE THREAD

**Issue by MPasadu** [neo4j/neo4j-dotnet-driver#382]
When just updating the nuget package, a lot of old code is no longer working. What we find so far is that the old ISession is no longer recognized.

What confuses me is, that the online API documentation still shows ISession but it's not found when using the nuget package.
Should we migrate all our codebase to IAsyncSession?

**Comment by zhenlineo** [comment]
Hi @MPasadu,

Sorry for the confusion. The `ISession` still exist, but it is located in a different package: https://www.nuget.org/packages/Neo4j.Driver.Simple/
To use our Simple session API, you need to have `Neo4j.Driver` and `Neo4j.Driver.Simple` installed.

The full driver includes
https://www.nuget.org/packages/Neo4j.Driver/
https://www.nuget.org/packages/Neo4j.Driver.Simple/
https://www.nuget.org/packages/Neo4j.Driver.Reactive/

You can choose freely which API you would like to use. 
We will provide an upgrade guide soon. Be free to ask any questions regarding upgrading in this thread.

**Comment by MPasadu** [comment]
@zhenlineo 
thank you for the great support!
I will look into these packages.

**Comment by technige** [comment]
Closing this issue as the original question has now been answered.

Separately, a driver upgrade guide is still pending.
