### ISSUE TITLE
[Suggestion] TransactionConfig can be made internal in 4.0.0?

### ISSUE THREAD

**Issue by andreycha** [neo4j/neo4j-dotnet-driver#386]
Hi,

As version 4.0.0 of the driver now favors usage of `TransactionConfigBuilder` and there is no public API which accepts or exposes `TransactionConfig`, it seems like it can be made internal. Although formally it's a breaking change, in fact it should not affect anyone.

**Driver version**: .NET driver 4.0.0

**Comment by technige** [comment]
Related to #387

**Comment by zhenlineo** [comment]
We've added this PR https://github.com/neo4j/neo4j-dotnet-driver/pull/399 to actually to allow users to access to TransactionConfig after created in case anyone would like to read the config after it is created.
