### ISSUE TITLE
IStatementResult needs to be IDisposable because of IPeekingEnumerator

### ISSUE THREAD

**Issue by IngvarKofoed** [neo4j/neo4j-dotnet-driver#39]
I think you should reconsider if IStatementResult _has_ to be IDisposable because it makes the client code that uses the Neo4j driver more complex and possible needless harder to use. 

I suggest to refactor the IPeekingEnumerator or the use of it so IStatementResult does not have to be IDisposable to make the user code less complex.

If you agree, Ill be happy to make a PR for a suggestion on how to do this :)

**Comment by zhenlineo** [comment]
I would close this issue as we have discussed on https://github.com/neo4j/neo4j-dotnet-driver/pull/50 and the PR now has been merged.
Pls be free to re-open this issue if you feel there is more to discuss.
