### ISSUE TITLE
Outdated Tutorial and Examples

### ISSUE THREAD

**Issue by nimasTT** [neo4j/neo4j-dotnet-driver#394]
neo4j .Net examples f.e. here https://neo4j.com/developer/dotnet/ or in your GitHub repository are outdated. The API's doesn't exist anymore. Can you please provide some new examples?

**Comment by zhenlineo** [comment]
Hi Thanks very much for reporting this to us.
The example still works, but you need to install:
```
Install-Package Neo4j.Driver.Simple -Version 4.0.0
```
