### ISSUE TITLE
How to see the Query getting executed

### ISSUE THREAD

**Issue by AbhishekTripathi** [neo4j/neo4j-dotnet-driver#395]
This is more of a feature request even though I wonder why it is missing in the first place. I have long complicated cypher queries. I was using Readify's client for neo4j but since that is not well maintained (based on commit history), I decided to start using the official drivers. The problem I have is that I can't see the query which is getting executed. **I want to be able to see the cypher query with its parameter filled in and the placeholders replaced.** The readify client has `ICypherFluentQuery` interface and has a `Query` property which gives me the `DebugQueryText`. This helps me diagnose the issue more efficiently. Please consider adding something similar possibly on `ISession` or `IAsyncSession` object.

**Comment by zhenlineo** [comment]
Hi @AbhishekTripathi 
You can use our logging on DEBUG level to see the query that get executed following this [guide](https://github.com/neo4j/neo4j-dotnet-driver#logging). 

You can also log yourself before passing the [Query](https://github.com/neo4j/neo4j-dotnet-driver/blob/4.0/Neo4j.Driver/Neo4j.Driver/Query.cs) to the session to [run](https://github.com/neo4j/neo4j-dotnet-driver/blob/4.0/Neo4j.Driver/Neo4j.Driver/IAsyncQueryRunner.cs#L75).

If the above methods do not address your problem, could you share some code example that how would you like to use this feature?

**Comment by AbhishekTripathi** [comment]
The suggestion of using an implementation of ILogger is helpful. However, it is not useful in all scenarios as it may require custom plumbing for projects where the target platform is the full framework. I would look into it and it might be useful for the under the hood operations going in the library.
Logging the query myself is not going to work and I think you missed the point here. What I want to achieve is the final literal query where the parameters are filled in with preferably proper escaping and input sanitization. See readify's documentation regarding this [here](https://github.com/Readify/Neo4jClient/wiki/cypher#debugging).

**Comment by zhenlineo** [comment]
Hi @AbhishekTripathi ,

This driver never alter the cypher query you put in. Whatever query you give to the driver, the driver will send the query as how it is given. It will not do any auto filling or change the query text ever. This driver never inspect the query, so it cannot give you a modified cypher query back.

**Comment by AbhishekTripathi** [comment]
Okay, I see it. The Readify client is also approximating the final query with substitution of parameters without escaping. It makes sense why it wouldn't be the responsibility of the driver itself. I will close this issue.
