### ISSUE TITLE
Internals in MessageResponseHandler for testing only is a code smell

### ISSUE THREAD

**Issue by IngvarKofoed** [neo4j/neo4j-dotnet-driver#41]
The class `MessageResponseHandler` : https://github.com/neo4j/neo4j-dotnet-driver/blob/1.0/Neo4j.Driver/Neo4j.Driver/Internal/Connector/MessageResponseHandler.cs
Has the following internals: 

```
internal Queue<IResultBuilder> ResultBuilders => new Queue<IResultBuilder>(_resultBuilders);
internal Queue<IRequestMessage> SentMessages => new Queue<IRequestMessage>(_sentMessages); 
```

This is a code smell that the OOP design is not complete and I think this should be refactored so that there is no need for internals for testing.

If you agree Ill happily create a PR for how to fix this code smell :)

**Comment by zhenlineo** [comment]
Yes, if you have some good ideas to design it better, yes, please.
I would say this is a good improvement so I would suggest to target it at 1.1.

**Comment by technige** [comment]
Closing this issue, please raise in PR if still desired.
