### ISSUE TITLE
Abstract interfaces into different assembly

### ISSUE THREAD

**Issue by bnayae** [neo4j/neo4j-dotnet-driver#433]
I suggest to split interfaces like: IResultCursor, IRecord, IResultSummary
into different assembly in order of being more dependency injection friendly.

I would like to abstract the handling of the query result without being coupled to the assembly of the implementation.

**Comment by AndyHeap-NeoTech** [comment]
Hi bnayae,  
Thank you for the suggestion, I will discuss this with the team and get back to you with our thoughts.

**Comment by AndyHeap-NeoTech** [comment]
We have decided to keep the interfaces in the same assembly for the time being. Thank you for the suggestion.
