### ISSUE TITLE
Failed to establish encrypted connection with server bolt

### ISSUE THREAD

**Issue by ZyCoderVs** [neo4j/neo4j-dotnet-driver#436]
## Failed to establish encrypted connection with server bolt

my server is windows server2012,dll version is  1.7.226.2
wrong is :

[Win32Exception (0x80004005): 给函数提供的标志无效]

[AuthenticationException: 调用 SSPI 失败，请参见内部异常。]
   System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception) +2415953
   System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) +77
   System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) +191
   System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest) +206
   System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult) +854
   Neo4j.Driver.Internal.Connector.TcpSocketClient.Connect(Uri uri) +150

[SecurityException: Failed to establish encrypted connection with server bolt://127.0.0.1:7687/.]

**Comment by AndyHeap-NeoTech** [comment]
Hi ZyCoderVs.  If the google translate of the error is correct: "Failed to call SSPI, see internal exception", then this looks like it might be an issue with the security certificate/setup on the server. Do you have any errors if you use an unsecured connection?

**Comment by AndyHeap-NeoTech** [comment]
Closing this issue. If you require further help then please reopen it.
