### ISSUE TITLE
Large result set can cause the 4.1.0 of driver to hang while iterating resultset

### ISSUE THREAD

**Issue by bcargill** [neo4j/neo4j-dotnet-driver#440]
- Neo4j version: Community 4.1.1
- Neo4j Mode: Single instance
- Driver version: dotnet 4.1.0 (4.0.2 seems to work)
- Operating system: Windows 10 with neo4j in docker

see git readme.md below for docker/neo4j config
**repro example** https://github.com/bcargill/Neo4jLargeResultBug  

Project has 3 unit tests:  
**Step1_CreateTestData**:   creates the data
**Step2_RunTest**:  runs the test
**Step3_DeleteTestData**:  you guessed it.... deletes the data

## Repro steps:
1. launch new neo4j docker image using config in readme
2. open test project in VS 2019 on Windows 10 (note neo4j driver version is **_4.0.2_**)
3. debug/run **Step1_CreateTestData**  (1 minute, generates 25,500 nodes, 25k relationships)
4. debug/run **Step2_RunTest**  (this should succeed, outputs info to debug window for monitoring, should iterate 25k nodes)
5. Update the Neo4j driver via nuget to **_4.1.0_** 
6. debug/run **Step2_RunTest** (this should fail by hanging...it does succeed sometimes, rerun Step2_RunTest if needed)

The record it fails on varies run to run on driver 4.1.0, it does succeed every once in a while.
If you delete the data and recreate it with the 4.1.0 driver it will sometimes hang creating the nodes.
I'm not seeing anything in the neo4j logs that indicates an error is happening.

**Comment by AndyHeap-NeoTech** [comment]
Hi bcargill. Thank you for raising a separate issue, this looks highly likely to be related to https://github.com/neo4j/neo4j-dotnet-driver/issues/437 that you have commented on, but is good to track them separately. I will update both issues as I work on figuring out what the underlying cause is.

**Comment by bcargill** [comment]
Agreed, #437 seemed to be solved by upping the memory settings so I thought this might be different (and I had the repro code).  Feel free to close this issue if you want.  Perhaps an additional clue, running the repro case against neo4j running through NeoDesktop on windows does NOT show the issue for me on driver v4.1.0.  Also, making the records smaller seems to increase the number of records it takes to cause the probelm.  Read buffer maybe?

**Comment by samgerene** [comment]
> Agreed, #437 seemed to be solved by upping the memory settings so I thought this might be different (and I had the repro code). Feel free to close this issue if you want. Perhaps an additional clue, running the repro case against neo4j running through NeoDesktop on windows does NOT show the issue for me on driver v4.1.0. Also, making the records smaller seems to increase the number of records it takes to cause the probelm. Read buffer maybe?

In my opinion #437 is not yet fixed, I verified on my side with increasing the memory as suggested did not resolve the problem. Using a previous version of the driver does _resolve_ it and that is how I will continue with my project for now.

**Comment by AndyHeap-NeoTech** [comment]
Hi samgerene, You are correct, the fix for #437 and this issue is currently in progress, I'm hoping to have an update today.

**Comment by AndyHeap-NeoTech** [comment]
Hi @bcargill.  I have a potential fix for this issue in a fork. Would you be willing test the fix against your local setup? 
It has passed everything here, but I would also like to test it against the 'original'.  If you are willing then please get the fork from https://github.com/AndyHeap-NeoTech/neo4j-dotnet-driver and use the Neo4j.Driver.csproj as your dependency rather than the Nuget package...it should just drop in.

**Comment by bcargill** [comment]
The branch seems to have fixed my issue.  Thanks!

**Comment by AndyHeap-NeoTech** [comment]
That is great news. If the other tests pan out I will be releasing a minor version onto NuGet later today, version 4.1.1

**Comment by AndyHeap-NeoTech** [comment]
Release 4.1.1 has now been made available on NuGet.  Thank you for your input and help.
