### ISSUE TITLE
[Types] Use DateOnly and TimeOnly

### ISSUE THREAD

**Issue by WhatzGames** [neo4j/neo4j-dotnet-driver#601]
For the Cyphertypes Date and time there are matching types in .net 6.
Considering an upgrade DateOnly and TimeOnly could be used to to reflect these types.

**Comment by thelonelyvulpes** [comment]
Hi @WhatzGames I have added the types in our net6 upgrade

Kind regards.

**Comment by thelonelyvulpes** [comment]
@WhatzGames, these types are now available in 5.X drivers.
