### ISSUE TITLE
General question regarding cypher error detection in multiple transactions

### ISSUE THREAD

**Issue by MPasadu** [neo4j/neo4j-dotnet-driver#647]
Hey neo4jdriver team,

I've just recently updated to the latest neo4j version and .net driver version.
When having one large transaction with multiple WriteTransactions and there is a single exception thrown, the exception shows up when the transaction is committed at the very end. So e.g. errors in cyphers are thrown in one exception at the end. You can't see which WriteTransaction actually has the issue.

The exception stacktrace only shows the line number of the commit. There is also no information what the actual cypher was that caused the error. Imagine 20-50 WriteTransactions with huge cyphers and at the end all information I seem to have is for example:

_"Can't create node `test` with labels or properties here. The variable is already declared in this context"_

Currently I have to go through all the WriteTransactions / cyphers that use the 'test' node to find the culprit. Clearly there must be an easier way?

**Comment by thelonelyvulpes** [comment]
Hi @MPasadu,
I'll try to give you some help but it will be easier to debug with some concrete code, so if you could share what it looks like without the actual cypher that'd be great.

When you do a write, you should consume the cursor that is returned by the `IAsyncTransaction.Run` This should immediately surface any errors from a query.

```
await session.WriteTransactionAsync(async tx => {
    var cursor = await tx.RunAsync("CREATE (:Example { 'ex': $val })", new { val = 10 });
    await cursor.ConsumeAsync(); // <- will raise any errors from RunAsync
});
```

I hope this helps.

**Comment by MPasadu** [comment]
Hey @thelonelyvulpes 
thanks for this. I guess it's an issue with our legacy code. We have joined neo4j very early on and are still using the synchronous library duo to the huge size of the codebase. 

It's basically build like this:

```
using (var session = driver.Session())
{
                _ = session.WriteTransaction(tx =>
                {
                    MethodWithRun1(tx);
                    MethodWithRun2(tx);
                    MethodWithRun3(tx);
                    // more of them
                });
}
```

So the transactions are chained together. When one fails all is reverted back. But it also means the error only surfaces when it went through all of the code. And the exception only shows the initial .WriteTransaction line.

**Comment by MPasadu** [comment]
EDIT: Accidentally hit the close issue button. Sorry.

**Comment by MPasadu** [comment]
EDIT: Accidentally hit the close issue button.

**Comment by thelonelyvulpes** [comment]
@MPasadu the synchronous library also exposes a consume method for the cursors.
```
_ = session.WriteTransaction(tx =>
{
    tx.Run("Create node").Consume(); <- will throw immediately.
    tx.Run("Create node").Consume();
    tx.Run("Create node").Consume();
    return 1;
});
```

**Comment by MPasadu** [comment]
@thelonelyvulpes 

Thank you! This seems to be what I was missing. Is this considered best practice when dealing with lots of chained cyphers in a  synchronous way?

**Comment by thelonelyvulpes** [comment]
If you want to commit all or nothing this is absolutely the way to go.

**Comment by MPasadu** [comment]
Thanks for the help!
