### ISSUE TITLE
"Routing table is updated" info log on every transaction

### ISSUE THREAD

**Issue by Aaronmsv** [neo4j/neo4j-dotnet-driver#653]
Hi,

Every time I execute a transaction the following information log gets printed:

```
info: MyService.Loggers.Neo4jLogger[0]
      Routing table is updated => RoutingTable{database=neo4j, routers=[neo4j://localhost:7687/], writers=[neo4j://localhost:7687/], readers=[neo4j://localhost:7687/], expiresAfter=300s}
```
Is this normal?

**Neo4j Version:** 5.1.0  Community  
**Neo4j Mode**: Single instance  
**Driver version**: .NET driver 5.1.0
**Operating System:** Linux 6.0.2-arch1-1 x86_64

**Comment by thelonelyvulpes** [comment]
If you are using a single instance you can specify the bolt scheme and this will avoid this issue.
You need to specify which database you are attempting to connect to when opening a session.

If you are still seeing this message after setting the database on the open of a session please share anything you can.

**Comment by Aaronmsv** [comment]
Hi @thelonelyvulpes,

Indeed, when using `bolt://localhost` instead of `neo4j://localhost` as URI, then the log doesn't get printed anymore. I'll also update the code to specify the database.

Thanks.

**Comment by thelonelyvulpes** [comment]
Glad to hear it is resolved.
Going to close this issue out, If you need further assistance please re-open it.
