### ISSUE TITLE
Exception for "DisposeAsync" after update to 5.5.0

### ISSUE THREAD

**Issue by DarthSonic** [neo4j/neo4j-dotnet-driver#678]
After updating Neo4j,Driver.Signed nuget package to v5.5.0 we get exception on ConnectAsync():

`System.TypeLoadException: 'Die Methode "DisposeAsync" im Typ "Neo4jClient.DriverWrapper" der Assembly "Neo4jClient, Version=5.1.3.0, Culture=neutral, PublicKeyToken=null" hat keine Implementierung.'`

Autotranslation:

`System.TypeLoadException: 'The method "DisposeAsync" in the type "Neo4jClient.DriverWrapper" of the assembly "Neo4jClient, Version=5.1.3.0, Culture=neutral, PublicKeyToken=null" has no implementation.'`

Solution:

Downgrading to v5.4.0

**Comment by thelonelyvulpes** [comment]
Hi @DarthSonic I think this is an incompatibility between the driver and Neo4jClient.
Neo4jClient's `DriverWrapper` extends the driver's `IDriver` interface which now extends IAsyncDisposable. This more an issue with https://github.com/DotNet4Neo4j/Neo4jClient.

So until Neo4jClient is updated to support the new driver they will be incompatible together.

**Comment by cskardon** [comment]
Neo4jClient `5.1.4` has been published with this in, so please give it a whirl.
