### ISSUE TITLE
.net driver NEVER reuses a connection

### ISSUE THREAD

**Issue by vikingivar** [neo4j/neo4j-dotnet-driver#686]
Hello all, my first post.

I am using neo4j to create a framework based on nodes and relations.

Opened my system today for a demonstration, for the 1000th time.
But this time the .net driver refuses to ever reuse a connection. So after 100 queries, the pool
has no available connections, and it is full, so after a while it says that:
"Failed to obtain a connection from pool within 00:01:00"

This is even a problem if I use:
WithMaxConnectionLifetime(TimeSpan.FromSeconds(10)) in the driver settings. 

The connections just never become available again. Something locks them.

I can use both Session.Run and Transaction.Run with using. No difference. I use the simple, not async
version because it was easier to find info about that when I wrote the code.

I have checked the neo4j browser, and yes, all 100 connections are there. And stays there until I have closed my c# application. I can change the number of connections in the pool, to say 10, but the behavior stays the same. But after 10 connections, that is.

The code has been working for years. And today it decided that, nope, won't work.
( of course during a presentation )

I have updated the driver and neo4j server to latest version. 

I didn't change anything. It worked yesterday. But not today. And I have restarted everything. Nope. Won't work.

There is no exception, the queries that does get through work as they should. The database is not corrupted. Everything works as it should in the Neo4j browser.  The database log says nothing.

Any ideas why connections gets magically locked would be much appreciated.

/eric

**Comment by thelonelyvulpes** [comment]
Hi @vikingivar thanks for reporting this issue.
Which version are/were you using, just trying to work out when it stopped working for you.
Which server version & configuration (i.e. cluster, multi-db)?
What configuration do you have your drivers & sessions (ConnectionAcquisitionTimeout)
Are you using the simple driver in the context of async?

**Comment by vikingivar** [comment]
Hi @thelonelyvulpes,
Today I started my computer and ... it worked again!, but... there is now another bug. Should be related. 
When my program execute: 
 using var tx = session.BeginTransaction();
there is an StackOverflowException thrown. And alas, not much info there: 
![exception](https://user-images.githubusercontent.com/106903611/221224857-a517c21f-bf8a-4b3c-83d4-1a91c87ec6f3.png)

So one wonder why these weird errors creep up.

**Comment by thelonelyvulpes** [comment]
That's very odd, Do you have loop in the transaction's metadata?
Any context you can add will help with resolving your issues.
