### ISSUE TITLE
TryVerifyConnectivityAsync is not implemented after 5.7.0 update

### ISSUE THREAD

**Issue by DarthSonic** [neo4j/neo4j-dotnet-driver#696]
![image](https://user-images.githubusercontent.com/3968605/230400054-9dd20853-a307-4c26-8c08-0cac5754b004.png)

TryVerifyConnectivityAsync is not implemented after 5.7.0 update

**Comment by thelonelyvulpes** [comment]
Hi DarthSonic

This seems like an issue with [Neo4jClient](https://github.com/DotNet4Neo4j/Neo4jClient) and not the driver.
