### ISSUE TITLE
Driver cannot Create Nodes from POCOs

### ISSUE THREAD

**Issue by simon-hardy** [neo4j/neo4j-dotnet-driver#73]
Self explanatory.

**Comment by zhenlineo** [comment]
As you could find in the [driver doc](http://neo4j.com/docs/developer-manual/3.0/index.html#types), the Node, Path and Relationship are types that only valid for return values. 

May I ask why do you need to create a `INode` object in your app? Could you give me an example that requires creation of a node explicitly?

**Comment by IngvarKofoed** [comment]
Could you give a use case for it ?

**Comment by zhenlineo** [comment]
I am closing this issue as the problem the issue wants to address is unclear. Please be free to reopen this issue if you get a better explanation or example of the problem you are having.
