### ISSUE TITLE
Getting results from generic nodes 

### ISSUE THREAD

**Issue by josephsctan** [neo4j/neo4j-dotnet-driver#811]
**Is your feature request related to a problem? Please describe.**
Seems to be difficult to return generic nodes if we don't know the properties before hand, because `Neo4j.Driver.Internal.Types.Node` is internal. E.g., I'm building an interface that lets the end user specify their database and a query, so it is not possible to map results, since `MATCH (n) RETURN n` can return any kind of entity, having any number of properties. 
The package does not have an easy way to iterate over the available **Labels** and **Properties**  of the results because the `Node` is internal.

**Describe the solution you'd like** 
Make `Neo4j.Driver.Internal.Types.Node`  public.

**Describe alternatives you've considered**
Reverse engineer Neo4j.Driver.Internal.Types.Node into a local class, `Neo4jDriverTypesNode`, and use "Deserialize-Cast" to convert the generic nodes returned from  `driver.ExecutableQuery` into objects of type `Neo4jDriverTypesNode` . It works, but making `Neo4j.Driver.Internal.Types.Node` public would be so much easier.

**Comment by thelonelyvulpes** [comment]
@josephsctan The drivers exposes `IEntity`, `INode`, `IRelationship` and `IPath`, These can be mapped to, if you have a need for the concrete class, please explain that.
