### ISSUE TITLE
Very high memory usage when loading MATCH results

### ISSUE THREAD

**Issue by shift-evgeny** [neo4j/neo4j-dotnet-driver#85]
With #83 fixed `session.Run("MATCH (n) RETURN n")` ran to completion, but it used 11.4 GB RAM by the end. That seems like far too much considering that the original CSV data was only about 700-800 MB. The database contained just under 10M nodes, each with 3 string properties and 1 int property. (The Neo4j server process used 3.5 GB RAM, by the way, which still seems like a lot.)

**Comment by genez** [comment]
The issue is still evident in 1.1.0-M2

**Comment by zhenlineo** [comment]
@genez Could you give me the full code of how you running this `session.Run("MATCH (n) RETURN n")`? I would like to know how you consumed the result?

**Comment by genez** [comment]
my fault. I was not trying against updated binary. 
will post another issue regarding dotnet restore failing on linux

**Comment by technige** [comment]
@genez can you confirm whether or not this is still an issue?

**Comment by genez** [comment]
I am going to perform some experiments in the next weeks.
Now I am committed on other tasks and cannot confirm the issue.

Please close it, I will eventually open another issue with more details

------ Original Message ------

**Comment by zhenlineo** [comment]
Closing this issue now, and pls be free to open a new one if you still find same issue in the latest drivers.
