### ISSUE TITLE
Proper DeadlockDetectedException handling

### ISSUE THREAD

**Issue by drgraduss** [neo4j/neo4j-dotnet-driver#87]
Hi,

what would be a proper way of catching `DeadlockDetectedException`. I see `TransientException`. Does `TransientException.Code` contain actual neo4j error name which I can use? In this case `DeadlockDetectedException`.

Thanks

**Comment by drgraduss** [comment]
I found that the actual code should be `Neo.TransientError.Transaction.DeadlockDetected`.

Could we introduce these error codes in the driver to be able to reference them?

**Comment by zhenlineo** [comment]
The driver needs the server to send the code first. Will investigate on this and come back to you. But expecting a bit longer waiting time than a normal driver only issue.

**Comment by zhenlineo** [comment]
https://github.com/neo4j/neo4j/pull/7463
Also more work will follow to clarify what behaviour the driver would take after these errors, such as rollback tx, close session, etc. And also examples, recommendations for driver users will be added for how to deal with these error.
Sorry for a bit random right now.

**Comment by zhenlineo** [comment]
I am closing this issue as the server already surfaced the DealockDetectedException to the client side. 
The cypher statement that raises ClientException or TransientException could be retried, while DatabaseException will result in connection termination. 

Please be free to raise another issue if you get more questions.
