### ISSUE TITLE
Parse only the parameters needed to run statement

### ISSUE THREAD

**Issue by mariomeyrelles** [neo4j/neo4j-dotnet-driver#93]
Good morning Sirs,

Sometimes I have a type with many fields. And sometimes, it's much easier to just pass the type to the statement and execute the command. 

The main problem is that the driver tries to read and parse all the parameters, even when I'm not using them on the query itself. For example, I want to create and user with **Id** as string and **name** as string. But the type itself also has more fields like **Date of Birth**, that won't be used inside the statement but can throw errors like _"cannot understandvalue with type System.DateTime"_ and so on.

Of course, I can use many strategies to prepare the statements of the parameter. But, is there a way to just try to parse the parameters that actually will be used, ignoring additional parameters that actually won't be used?

**Comment by zhenlineo** [comment]
It is a nice idea to just pack the parameters that are needed. However the driver dose not do any Cypher parsing but just passes the Cypher to the server. So right now the driver is not clever enough to know what parameters are needed for the Cypher statement. Building a simple Cypher parser is not planned for drivers. So unfortunately we will not be able to only pack the parameters that are used in the Cypher statement. 

The recommended way to provide the parameters are actually via a dictionary, such as:

```
var result = session.Run(
"MATCH (knight:Person:Knight) WHERE knight.castle = {castle} RETURN knight.name AS name",
    new Dictionary<string, object> { { "castle", "Camelot" } });
```

So I would recommend you to pre-parse your parameters in a dictionary and call `Run(string, Dictionary)`.

Sorry for not really being helpful :)

**Comment by mariomeyrelles** [comment]
Sure... I totally understand the point and in fact, I moved to a dictionary-based solution and it worked well.

Thanks for you time :)
