### ISSUE TITLE
Driver throwing Sockets exception

### ISSUE THREAD

**Issue by mperrenoud** [neo4j/neo4j-dotnet-driver#98]
I have an ASP.NET Core project setup and I'm trying to get connected to my Neo4j server. I have the following references:

```
"dependencies": {
  "Microsoft.AspNetCore.Mvc": "1.0.0",
  "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
  "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
  "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
  "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
  "Microsoft.Extensions.Configuration.Json": "1.0.0",
  "Microsoft.Extensions.Logging": "1.0.0",
  "Microsoft.Extensions.Logging.Console": "1.0.0",
  "Microsoft.Extensions.Logging.Debug": "1.0.0",
  "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
  "Microsoft.NETCore.App": {
    "version": "1.0.0",
    "type": "platform"
  },
  "Neo4j.Driver": "1.0.0",
  "Newtonsoft.Json": "9.0.1",
  "rda.SocketsForPCL": "1.2.2"
}
```

I'm building a driver like this inside the `WebApiConfig` class:

```
var url = config["ConnectionStrings:Neo4j"];
var driver = GraphDatabase.Driver(url, AuthTokens.Basic(config["Neo4j:Username"], config["Neo4j:Password"]));

Neo4jDriver = driver;
```

I'm then using the driver like this:

```
using (var session = WebApiConfig.Neo4jDriver.Session())
{
    session.Run("CREATE (a:Person {name:'Arthur', title:'King'})");
    return session.Run("MATCH (a:Person) WHERE a.name = 'Arthur' RETURN a.name AS name, a.title AS title");
}
```

However, this `WebApiConfig.Neo4jDriver.Session()` is throwing an exception:

> An exception of type 'System.NotImplementedException' occurred in Neo4j.Driver.dll but was not handled in user code
> 
> Additional information: The empty PCL implementation for Sockets was loaded. Ensure you have added the Sockets nuget package to each of your platform projects.

**Comment by zhenlineo** [comment]
We will look into this. But meanwhile we had this old [movies example](https://github.com/neo4j-examples/movies-dotnet-bolt), maybe it might help you a bit?

**Comment by mperrenoud** [comment]
Yeah I checked that movies example so that I could effectively mimic it. For example, I made sure based of the `packages.config` that I was referencing the right NuGet packages. I also made sure I was using the same process to the connect. I even verified the port on my Neo4j server to make sure it was the default that would be produced in the Driver library and it was. 

I will double check the `packages.config`.

**Comment by zhenlineo** [comment]
Wait, are you targeting at .net core? This driver is not possible for .net core project, as we used the Pcl lib for sockets is not compatible. The work to support .net core is a community work https://github.com/neo4j-contrib/neo4j-dotnetcore-driver

**Comment by mperrenoud** [comment]
@zhenlineo so I modified the version to be `1.0.2` per the [NuGet](https://www.nuget.org/packages/Neo4j.Driver) link provided in that repo's read me. Upon leveraging that version I'm still getting this error:

> An exception of type 'System.NotImplementedException' occurred in Neo4j.Driver.dll but was not handled in user code
> 
> Additional information: The empty PCL implementation for Sockets was loaded. Ensure you have added the Sockets nuget package to each of your platform projects.

I've tried with the following connection strings:
- `bolt://localhost`
- `bolt://localhost:7687`

I've also verified that my Neo4j server is executing off port 7687.

# UPDATE

I also tried `1.1.0-M01` but receive the same error.

**Comment by zhenlineo** [comment]
@mperrenoud The reason is probably because you are building a ASP.NET core project. The driver does NOT support .NET core at this moment. The error message showed that the PCL lib our driver built upon is missing the impl for sockets in .NET core platform. So unfortunately we could hardly help with your problem :(

**Comment by mperrenoud** [comment]
I'm confused. In your response above you mentioned that if I were building a .NET Core application I could use the other repo? Is that version _not actually deployed_ to the NuGet feed even though its read me says so? Is that the deal? Because if so the read me should probably be updated to indicate it has to be built manually.

**Comment by zhenlineo** [comment]
Sorry for the confusion. 

This official .NET bolt driver does not support .NET core projects.

The other repo is a community project aiming to make a .NET bolt driver that support .NET core based on this official driver. The other repo is not maintained by us. But I just checked that repo for you and I do not think it published any functional driver that you could use in your .NET core project. The code is also not useable directly without any modification for a .NET core project. As I did not see any PR or commits besides other the original commits. So if you want to use it in your project, you might need to first submit a few PR to that repo to make it compile and run on .NET core.

I do not know if there are other good community .NET bolt drivers that support .NET core. 

So I would suggest you
1) setting up a project type that you could use this official driver or
2) finding a good community .NET driver that support .NET core. It could use either bolt binary protocol or old HTTP endpoint or
3) fixing the community .NET driver in the other repo and use it in your project or
4) write your own a simple driver for Neo4j

So sorry that we do not support .NET core and could hardly help with the problem you mentioned in this issue.

**Comment by zhenlineo** [comment]
Hi,

A good news is that from 1.1.0-M02, this driver will support .net core projects. So please be free to try it out. But still, keep in mind that the milestone drivers are not ready for production.

Best,
Zhen
